import { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const generate = (type: string, items: string[]) =>
  items.map((item) => `bagu/${type}/${item}`)

const factory = (type: string) => {
  return (items: string[]) => generate(type, items)
}

const generateHTMLCategory = factory('html-css')
const generateJSCategory = factory('js')
const generateTSCategory = factory('ts')
const generateVueCategory = factory('vue')
const generateReactCategory = factory('react')
const generateNetworkCategory = factory('network')
const generateOSCategory = factory('os')
const generateBrowserCategory = factory('browser')
const generateEngineeringCategory = factory('engineering')
const generateNodeCategory = factory('nodejs')
const generateCodeCategory = factory('code')
const generateInterviewCategory = factory('interview')
const generateEverythingCategory = factory('everything')

export default {
  bagu: [
    {
      type: 'category',
      label: 'HTML CSS',
      items: generateHTMLCategory([
        'html',
        'css',
        'bfc',
        '层叠上下文',
        '重排重绘',
      ]),
    },
    {
      type: 'category',
      label: 'JS',
      items: generateJSCategory([
        'FormData',
        '浮点数精度',
        'javascript-basis',
        'javascript-advanced',
        'v8',
        'regexp',
        'es6-plus',
      ]),
    },
    {
      type: 'category',
      label: 'TS',
      items: generateTSCategory(['basis', 'type-challenges']),
    },
    {
      type: 'category',
      label: 'Vue',
      items: generateVueCategory(['basis', 'source-code']),
    },
    {
      type: 'category',
      label: 'React',
      items: generateReactCategory(['base', 'principle', 'react-native']),
    },
    {
      type: 'category',
      label: '计算机网络',
      items: generateNetworkCategory([
        'network-model',
        'http',
        'https',
        'tcp',
        'udp',
        'ip',
        'authentication',
      ]),
    },
    {
      type: 'category',
      label: '操作系统',
      items: generateOSCategory(['hardware']),
    },
    {
      type: 'category',
      label: '浏览器',
      items: generateBrowserCategory([
        'browser-security',
        'cache',
        'event-loop',
        'source-load',
        'composition',
        'vitals',
      ]),
    },
    {
      type: 'category',
      label: '工程化',
      items: generateEngineeringCategory([
        'engineering',
        'eslint',
        'package-management-tool',
        'vite',
        'webpack',
        'esbuild',
        'micro-frontend',
      ]),
    },
    {
      type: 'category',
      label: 'Node.js',
      items: generateNodeCategory(['basic', 'nest', 'principles']),
    },
    {
      type: 'category',
      label: '代码篇',
      items: generateCodeCategory([
        'jsAchieve',
        'debounce-thorttle',
        'promise',
        'algorithm',
      ]),
    },
    {
      type: 'category',
      label: '杂货箱',
      items: generateEverythingCategory(['vuera', 'design-patterns']),
    },
    {
      type: 'category',
      label: '面经',
      items: generateInterviewCategory([
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
      ]),
    },
  ],
  note: [
    {
      type: 'autogenerated',
      dirName: 'note',
    },
  ],
  record: [
    {
      type: 'autogenerated',
      dirName: 'record',
    },
  ],
} satisfies SidebarsConfig
