import { SidebarsConfig } from '@docusaurus/plugin-content-docs'

export default {
  bagu: [
    {
      type: 'category',
      label: 'HTML CSS',
      items: [
        'bagu/html-css/html',
        'bagu/html-css/css',
        'bagu/html-css/bfc',
        'bagu/html-css/层叠上下文',
        'bagu/html-css/重排重绘',
      ],
    },
    {
      type: 'category',
      label: 'JS',
      items: [
        'bagu/js/FormData',
        'bagu/js/浮点数精度',
        'bagu/js/javascript-basis',
        'bagu/js/javascript-advanced',
        'bagu/js/v8',
        'bagu/js/regexp',
        'bagu/js/es6-plus',
      ],
    },
    {
      type: 'category',
      label: 'TS',
      items: ['bagu/ts/basis', 'bagu/ts/type-challenges'],
    },
    {
      type: 'category',
      label: 'Vue',
      items: ['bagu/vue/basis', 'bagu/vue/source-code'],
    },
    {
      type: 'category',
      label: 'React',
      items: [
        'bagu/react/base',
        'bagu/react/principle',
        'bagu/react/react-native',
      ],
    },
    {
      type: 'category',
      label: '计算机网络',
      items: [
        'bagu/network/network-model',
        'bagu/network/http',
        'bagu/network/https',
        'bagu/network/tcp',
        'bagu/network/udp',
        'bagu/network/ip',
        'bagu/network/authentication',
      ],
    },
    {
      type: 'category',
      label: '浏览器',
      items: [
        'bagu/browser/browser-security',
        'bagu/browser/cache',
        'bagu/browser/event-loop',
        'bagu/browser/source-load',
        'bagu/browser/composition',
        'bagu/browser/vitals',
      ],
    },
    {
      type: 'category',
      label: '工程化',
      items: [
        'bagu/engineering/engineering',
        'bagu/engineering/eslint',
        'bagu/engineering/package-management-tool',
        'bagu/engineering/vite',
        'bagu/engineering/webpack',
        'bagu/engineering/esbuild',
        'bagu/engineering/micro-frontend',
      ],
    },
    {
      type: 'category',
      label: 'Node.js',
      items: [
        'bagu/nodejs/basic',
        'bagu/nodejs/nest',
        'bagu/nodejs/principles',
      ],
    },
    {
      type: 'category',
      label: '代码篇',
      items: [
        'bagu/code/jsAchieve',
        'bagu/code/debounce-thorttle',
        'bagu/code/promise',
        'bagu/code/algorithm',
      ],
    },
    {
      type: 'category',
      label: '杂货箱',
      items: ['bagu/everything/vuera', 'bagu/everything/design-patterns'],
    },
    {
      type: 'category',
      label: '面经',
      items: [
        'bagu/interview/1',
        'bagu/interview/2',
        'bagu/interview/3',
        'bagu/interview/4',
        'bagu/interview/5',
        'bagu/interview/6',
        'bagu/interview/7',
        'bagu/interview/8',
        'bagu/interview/9',
        'bagu/interview/10',
        'bagu/interview/11',
      ],
    },
  ],
  note: [
    {
      type: 'autogenerated',
      dirName: 'note',
    },
  ],
  record: [
    {
      type: 'autogenerated',
      dirName: 'record',
    },
  ],
} satisfies SidebarsConfig
